@echo off
echo Starting StreamX Backend...
start cmd /k "cd backend && pip install -r requirements.txt && python main.py"

echo Starting StreamX Frontend...
start cmd /k "cd frontend && npm install && npm run dev"
