@echo off
echo Starting IronGate v7...
echo.

echo Starting Backend...
start "IronGate Backend" cmd /k "cd backend && python main.py"

echo Waiting for backend to initialize...
timeout /t 3 /nobreak >nul

echo Starting Electron App...
cd electron
npm start
